"""user manager

Revision ID: 4587fda03d19
Revises: c00e3d390f1b
Create Date: 2018-11-21 23:13:21.967821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4587fda03d19'
down_revision = 'c00e3d390f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userp')
    # ### end Alembic commands ###
