"""info table

Revision ID: faa8032136ee
Revises: 4587fda03d19
Create Date: 2018-11-21 23:42:59.060166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa8032136ee'
down_revision = '4587fda03d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('Infoid', sa.Integer(), nullable=False),
    sa.Column('Infotitle', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Infoid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    # ### end Alembic commands ###
